// <auto-generated />
using System;
using BookingSystemRRC.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BookingSystemRRC.Migrations
{
    [DbContext(typeof(BookingDbContext))]
    partial class BookingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BookingSystemRRC.Models.Booking", b =>
                {
                    b.Property<int>("BookingNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BookingComment")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateTimeEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTimeStart")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GuestNumbe")
                        .HasColumnType("int");

                    b.Property<int?>("GuestNumber1")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfPeople")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WeekDays")
                        .HasColumnType("int");

                    b.HasKey("BookingNumber");

                    b.HasIndex("GuestNumbe");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("BookingSystemRRC.Models.Guest", b =>
                {
                    b.Property<int>("GuestNumbe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuestComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("int");

                    b.HasKey("GuestNumbe");

                    b.ToTable("Guests");
                });

            modelBuilder.Entity("BookingSystemRRC.Models.RoomBooking", b =>
                {
                    b.Property<int>("RoomBookingNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("GuestNumbe")
                        .HasColumnType("int");

                    b.Property<int>("WeekDay")
                        .HasColumnType("int");

                    b.HasKey("RoomBookingNumber");

                    b.HasIndex("GuestNumbe");

                    b.ToTable("RoomBookings");
                });

            modelBuilder.Entity("BookingSystemRRC.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BookingSystemRRC.Models.Booking", b =>
                {
                    b.HasOne("BookingSystemRRC.Models.Guest", "Guest")
                        .WithMany("Bookings")
                        .HasForeignKey("GuestNumbe");

                    b.Navigation("Guest");
                });

            modelBuilder.Entity("BookingSystemRRC.Models.RoomBooking", b =>
                {
                    b.HasOne("BookingSystemRRC.Models.Guest", "Guest")
                        .WithMany("RoomBookings")
                        .HasForeignKey("GuestNumbe");

                    b.Navigation("Guest");
                });

            modelBuilder.Entity("BookingSystemRRC.Models.Guest", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("RoomBookings");
                });
#pragma warning restore 612, 618
        }
    }
}
